### ISSUE TITLE
RE2 PC background mask

### ISSUE THREAD

**Issue by yanmingsohu** [pmandin/reevengi#1]
The background image of the mask is stored with 'common/bin/roomcut.bin'

-------------------------------------------------
256 x 240x (2byte) is background image
-------------------------------------------------
256 x 16 x (2byte) is empty data
-------------------------------------------------
256 x 64 x (2byte) is background image clip x 4
-------------------------------------------------
256 x 1 x (2byte) is empty ?
-------------------------------------------------
256 x 256 x (1byte) is mask image
-------------------------------------------------

But there is a problem. It is wrong to map directly from the map data parsing mask to the screen. There seems to be some mysterious algorithm...

**Comment by pmandin** [comment]
Hello, and thanks for the info. In fact I had some time to dig more in this roomcut.bin file, and here is what I found:

Each ADT depacked file (which is in the roomcut.bin archive) contain 2 files: one raw 320x256 16 bits raw image (for the background), followed by a TIM image (mostly 320x128) which contains the masks for the background.
